import {Viewer} from './viewer.mjs';
import {Selfie} from './selfie.mjs';
import {PRACTICE_QUESTIONS} from './practice.mjs';
const $=s=>document.querySelector(s),main=$('#main');
const species=[
 {id:'maeng',name:'맹꽁이',latin:'Kaloula borealis',line:'작은 머리, 둥근 몸. 천천히 돌려보면 나만의 특징이 보여요.',facts:['둥근 몸통','짧은 다리','작은 머리'],detail:'앞발 4개 · 뒷발 5개 발가락. 뒷발에는 부분적인 물갈퀴가 있어요.',video:'40431293'},
 {id:'toad',name:'두꺼비',latin:'Bufo gargarizans',line:'눈 뒤쪽을 살펴볼까요? 타원형 귀밑샘과 피부의 돌기를 찾아봐요.',facts:['눈 뒤 귀밑샘','크고 작은 돌기','두툼한 몸'],detail:'색깔과 크기는 개체마다 달라요. 한 가지 특징만으로 판단하지 않아요.',audio:'./assets/toad-call.wav'},
 {id:'om',name:'옴개구리',latin:'',line:'등과 다리를 살펴봐요. 짧게 솟은 선들과 뾰족한 주둥이가 보여요.',facts:['짧은 융기선','뾰족한 주둥이','접힌 긴 뒷다리'],detail:'피부가 거칠다고 모두 두꺼비는 아니에요. 몸통과 다리도 함께 살펴봐요.',video:'40431369'}
];
let viewers=[],screen='home',studyIndex=0,question=null,answering=false,selfie=null,photoURL=null,practice=false,local=null,networkBusy=false;
const prefs={sound:true,haptic:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
try{Object.assign(prefs,JSON.parse(localStorage.getItem('songdo-prefs')||'{}'));}catch{}
function savePrefs(){try{localStorage.setItem('songdo-prefs',JSON.stringify(prefs));}catch{}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
let toastTimer;function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
function clear(){viewers.forEach(v=>v.dispose());viewers=[];selfie?.dispose();selfie=null;closeSound();$('#pause-cover')?.remove();if(photoURL){URL.revokeObjectURL(photoURL);photoURL=null;}}
function page(html,name){clear();screen=name;main.innerHTML=html;window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});}
function stage(id,{tag='',note='돌리고 확대해 보세요'}={}){return `<div class="stage" id="${id}" role="img" aria-label="회전하고 확대할 수 있는 3D 동물"><div class="stage-loading">작은 친구를 불러오는 중…</div><span class="stage-tag">${tag}</span>${note?`<span class="stage-note"><span class="stage-note-icon" aria-hidden="true">👆 ↔</span><span class="stage-note-text">${note}</span></span>`:''}</div>`;}
function view(id,opts={}){const viewer=new Viewer(document.getElementById(id),opts);viewer.reduced=prefs.reduced;viewers.push(viewer);return viewer.ready.then(()=>true).catch(()=>{toast('3D 표시를 확인해 주세요. WebGL을 지원하는 브라우저가 필요해요.');return false;});}
let audioContext;
function sfx(type){if(!prefs.sound||($('#sound-panel')&&!$('#sound-panel').hidden))return;try{audioContext??=new AudioContext();audioContext.resume();const t=audioContext.currentTime;
 const notes=type==='win'?[523,659,784]:type==='right'?[660,880]:type==='splash'?[180,100,260,80]:[480];
 notes.forEach((freq,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type==='splash'?'triangle':'sine';o.frequency.setValueAtTime(freq,t+i*.09);g.gain.setValueAtTime(0,t+i*.09);g.gain.linearRampToValueAtTime(.10,t+i*.09+.012);g.gain.exponentialRampToValueAtTime(.001,t+i*.09+.17);o.connect(g);g.connect(audioContext.destination);o.start(t+i*.09);o.stop(t+i*.09+.19);});}catch{}}
function splash(){sfx('splash');if(prefs.haptic&&navigator.vibrate)navigator.vibrate([65,40,90]);const root=$('#splash');root.replaceChildren();
 for(let i=0;i<(prefs.reduced?4:18);i++){const d=document.createElement('i');d.className='water-drop';d.style.cssText=`left:${Math.random()*100}%;top:${Math.random()*86}%;width:${25+Math.random()*110}px;height:${25+Math.random()*115}px;animation-delay:${Math.random()*.16}s`;root.append(d);}setTimeout(()=>root.replaceChildren(),1900);}
function foam(host){if(!host||prefs.reduced)return;for(let i=0;i<12;i++){const d=document.createElement('i');d.className='bubble';d.style.cssText=`left:${35+Math.random()*35}%;top:50%;--x:${Math.random()*80-40}px;animation-delay:${i*.06}s`;host.append(d);setTimeout(()=>d.remove(),2200);}}
async function api(path,data){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(`./api/${path}`,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data),signal:controller.signal});const j=await r.json().catch(()=>({error:'서버'}));if(!r.ok||j.error)throw Error(j.error==='서버'?'기록 서버에 연결할 수 없어요.':j.error||'연결을 확인해 주세요.');return j;}finally{clearTimeout(timer);}}
// Standalone static hosting has an explicitly labelled, unranked practice mode.
function shuffle(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);const j=bytes[0]%(i+1);[b[i],b[j]]=[b[j],b[i]];}return b;}
async function game(path,data){
 if(!practice)return api(path,data);
 if(path==='session'){local={index:0,score:0,duration:0,history:[],elapsed:0,state:'waiting',orders:PRACTICE_QUESTIONS.map(q=>shuffle(q.models?q.models.map(k=>({id:k,model:k})):q.options))};return {ok:true};}
 if(path==='question'){if(local.index===5)return {complete:true};const q=PRACTICE_QUESTIONS[local.index];return {...q,index:local.index,options:local.orders[local.index],visual:!!q.models,complete:false};}
 if(path==='result')return local;
 if(path==='ready'||path==='resume'){local.started=performance.now();local.state='active';return {ok:true};}
 if(path==='pause'){if(local.state==='active')local.elapsed+=performance.now()-local.started;local.state='paused';return {ok:true};}
 if(path==='answer'){const q=PRACTICE_QUESTIONS[local.index],correct=q.answer===data.answer,elapsed=Math.round(local.elapsed+performance.now()-local.started),r={correct,explain:q.explain,answer:q.answer,elapsed,id:q.id};local.duration+=elapsed;local.score+=Number(correct);local.history.push(r);local.index++;local.elapsed=0;local.state='waiting';return {...r,score:local.score,complete:local.index===5};}
}
function home(){page(`<section class="hero"><div class="hero-copy"><span class="pill">포항 송도 · 생태 탐험</span><h1>맹꽁이를<br><em>찾아주세요!</em></h1><p class="lead">닮은 듯 다른 세 친구.<br>보고, 듣고, 돌려보며 주인공을 찾아요.</p><button class="primary" id="start">작은 친구 만나기 <span class="arrow">↗</span></button><p class="muted">관찰 + 다섯 문제 + 맹꽁이 셀카 한 컷</p></div><div class="hero-art"><span class="art-tag">HELLO, LITTLE FRIEND</span><div class="hero-mystery" aria-hidden="true">누구를<br>만날까요<span>?</span></div><div class="art-caption">안내 게와 함께<b>작은 친구를 찾아요</b></div><div class="mini-guide" id="home-crab"></div></div></section><section class="steps"><div class="step"><span>01</span><div><b>보고, 듣고</b><small>세 친구를 천천히 관찰해요</small></div></div><div class="step"><span>02</span><div><b>찾고, 배우고</b><small>안내 게와 다섯 문제를 풀어요</small></div></div><div class="step"><span>03</span><div><b>우리, 함께</b><small>어깨 위 맹꽁이와 사진을 남겨요</small></div></div></section>`,'home');
 view('home-crab',{kind:'crab',interactive:false});$('#start').onclick=()=>{sfx('tap');study(0);};}
function study(index){studyIndex=index;const animal=species[index];page(`<div class="section-head"><button class="back" id="go-home">← 처음으로</button><span class="step-count">관찰 ${index+1} / 3</span></div><div class="progress"><div style="width:${(index+1)/3*100}%"></div></div><section class="study-layout"><div class="study-stage-wrap">${stage('animal',{tag:`FRIEND ${String(index+1).padStart(2,'0')}`})}<button class="stage-sound" id="listen" aria-label="${animal.name} 소리 듣기" aria-expanded="false" aria-controls="sound-panel">♫ 소리 듣기</button><section class="sound-panel" id="sound-panel" aria-label="${animal.name} 소리 재생" hidden><div class="sound-panel-head"><strong id="sound-title"></strong><button id="sound-close" aria-label="소리 닫기">닫기 ×</button></div><div id="sound-player"></div><p id="sound-credit"></p></section></div><div class="study-copy"><p class="eyebrow">반가워요, 나는</p><h2>${animal.name}</h2><p class="latin">${animal.latin||'Wrinkled frog'}</p><div class="study-keyfacts" aria-label="${animal.name}의 특징"><strong>한눈에 보는 특징</strong><div class="facts">${animal.facts.map(f=>`<span>${f}</span>`).join('')}</div></div><p class="lead">${animal.line}</p><p class="muted">${animal.detail}</p><div class="study-actions"><button class="primary" id="next-friend">${index===2?'문제 풀러 가기':'다음 친구 →'}</button></div><div class="small-links" aria-label="관찰할 친구 선택">${species.map((s,i)=>`<button class="${index===i?'current':''}" data-friend="${i}" aria-label="${s.name} 관찰">${i+1}</button>`).join('')}</div><p class="model-notice">형태 비교용 3D 시제품 · 교육 공개 전 생태 검수 예정</p></div></section>`,'study');
 view('animal',{kind:animal.id});$('#go-home').onclick=home;$('#listen').onclick=()=>$('#sound-panel').hidden?openSound(animal):closeSound();$('#sound-close').onclick=closeSound;$('#next-friend').onclick=()=>index<2?study(index+1):quizIntro();document.querySelectorAll('[data-friend]').forEach(b=>b.onclick=()=>study(Number(b.dataset.friend)));}
function openSound(animal){sfx('tap');viewers.forEach(v=>v.calling=animal.id==='maeng');$('#sound-title').textContent=`${animal.name}의 목소리`;
 if(animal.audio){$('#sound-player').innerHTML=`<audio controls autoplay src="${animal.audio}"></audio>`;$('#sound-credit').innerHTML='김용배 · 「두꺼비」 · 공유마당 CC BY<br>제공자가 두꺼비로 분류한 음원입니다. 종별 소리는 교육 공개 전 추가 검수합니다.';}
 else{$('#sound-player').innerHTML=`<iframe title="${animal.name} 실제 울음소리" src="https://player.vimeo.com/video/${animal.video}?autoplay=1&dnt=1" allow="autoplay; fullscreen" allowfullscreen></iframe><p><a href="https://vimeo.com/${animal.video}" target="_blank" rel="noopener">재생이 안 되면 원본에서 듣기 ↗</a></p>`;$('#sound-credit').textContent='국립환경과학원 도감 수록 소리 · 원본 Vimeo 플레이어 (인터넷 필요)';}
 $('#sound-panel').hidden=false;$('#listen').setAttribute('aria-expanded','true');}
function closeSound(){viewers.forEach(v=>v.calling=false);$('#sound-player')?.replaceChildren();const panel=$('#sound-panel');if(panel)panel.hidden=true;$('#listen')?.setAttribute('aria-expanded','false');}
function quizIntro(){const staticSite=location.hostname.endsWith('.github.io');page(`<section class="study-layout">${stage('intro-crab',{note:''})}<div class="study-copy"><p class="eyebrow">안내 게의 작은 미션</p><h2>잘 봤나요?<br>이제 복습할까요?</h2><p class="lead">방금 만난 세 친구의 특징을 떠올리며 문제를 풀어봐요.<br>틀려도 괜찮아요. 함께 배우면 돼요.</p><div class="facts"><span>다섯 문제</span><span>${staticSite?'순위 없는 연습':'정답 수 우선'}</span><span>${staticSite?'기록 저장 안 함':'풀이 시간만 기록'}</span></div><p class="muted">${staticSite?'정답 설명을 보며 연습할 수 있어요.':'관찰과 설명을 읽는 시간은 기록하지 않아요.'}<br>사진은 모든 친구가 찍을 수 있어요.</p><button class="primary wide" id="quiz-start">준비됐어요!</button><button class="ghost wide" id="study-again">친구들 다시 보기</button><div id="connection-error"></div></div></section>`,'intro');view('intro-crab',{kind:'crab'});$('#study-again').onclick=()=>study(0);$('#quiz-start').onclick=()=>startQuiz(staticSite);}
async function startQuiz(usePractice){if(networkBusy)return;networkBusy=true;practice=usePractice;$('#quiz-start').disabled=true;try{await game('session',{});await showQuestion();}catch(e){$('#connection-error').innerHTML='<p class="muted">순위 서버에 연결하지 못했어요. 기록 없이 연습할 수 있어요.</p><button class="secondary wide" id="practice-start">순위 없는 연습 시작</button>';$('#practice-start').onclick=()=>startQuiz(true);$('#quiz-start').disabled=false;}finally{networkBusy=false;}}
async function showQuestion(){const q=await game('question');if(q.complete)return results();question=q;answering=false;
 let choices;if(q.visual){choices=`<div class="quiz-picker" aria-label="살펴볼 친구">${q.options.map((o,i)=>`<button class="${i===0?'active':''}" data-pick="${i}" aria-pressed="${i===0}">${i+1}번 보기</button>`).join('')}</div><div class="choice-grid">${q.options.map((o,i)=>`<article class="choice-card ${i===0?'active':''}" data-choice="${i}">${stage('choice-'+i,{note:''})}<button disabled data-answer="${o.id}">이 친구예요 · ${i+1}번</button></article>`).join('')}</div>`;}else{choices=`<div class="question-body">${stage('question-model',{note:''})}<div class="text-choices">${q.options.map((o,i)=>`<button disabled data-answer="${o.id}">${i+1}. ${o.text}</button>`).join('')}</div></div>`;}
 page(`<div class="section-head"><span class="eyebrow" style="margin:0">${practice?'순위 없는 연습':'안내 게의 미션'}</span><span class="step-count">${q.index+1} / 5</span></div><div class="progress"><div style="width:${q.index/5*100}%"></div></div><div class="quiz-head"><h2>${q.title}</h2><p>${q.hint}</p></div>${choices}<div class="quiz-bottom" id="quiz-status">3D 친구들을 준비하고 있어요…</div><div id="feedback"></div>`,'quiz');
 document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-choice]').forEach(c=>c.classList.toggle('active',c.dataset.choice===b.dataset.pick));document.querySelectorAll('[data-pick]').forEach(c=>{c.classList.toggle('active',c===b);c.setAttribute('aria-pressed',String(c===b));});});
 const loaded=await Promise.all(q.visual?q.options.map((o,i)=>view('choice-'+i,{kind:o.model,angle:q.id==='final'?-1.05:.32})): [view('question-model',{kind:q.model})]);
 if(screen!=='quiz'||question!==q)return;
 if(loaded.some(ok=>!ok)){$('#quiz-status').textContent='3D를 표시하지 못했어요. 새로고침하거나 다른 브라우저에서 열어주세요.';return;}
 try{await game('ready',{index:q.index});document.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=false;b.onclick=()=>answer(b.dataset.answer);});$('#quiz-status').textContent='손가락으로 돌려본 뒤 친구를 골라주세요.';if(document.hidden)await pauseQuiz();}catch(e){toast('문제를 시작하지 못했어요. 처음부터 다시 시작해 주세요.');$('#quiz-status').innerHTML='<button class="secondary" id="restart">다시 시작하기</button>';$('#restart').onclick=quizIntro;}}
async function answer(id){if(answering||screen!=='quiz')return;answering=true;document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);
 try{const r=await game('answer',{index:question.index,answer:id});question=null;
 const f=$('#feedback');f.className=`feedback ${r.correct?'':'wrong'}`;f.innerHTML=`<div><div class="guide-reaction" id="reaction-crab"></div><h3>${r.correct?'맞았어요! 잘 관찰했어요.':'괜찮아요! 함께 다시 알아봐요.'}</h3><p>${r.explain}</p></div><button class="primary" id="continue">${r.complete?'결과 보기':'다음 문제 →'}</button>`;
 await view('reaction-crab',{kind:'crab',interactive:false});if(r.correct)sfx('right');else{foam($('#reaction-crab'));splash();}
 $('#quiz-status').textContent='설명을 읽는 동안에는 시간이 기록되지 않아요.';$('#continue').onclick=()=>showQuestion().catch(e=>toast('연결을 확인하고 다시 눌러주세요.'));f.scrollIntoView({behavior:prefs.reduced?'instant':'smooth',block:'nearest'});
 }catch(e){answering=false;toast(e.message);document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=false);}}
async function pauseQuiz(){if(screen!=='quiz'||!question||answering||$('#pause-cover'))return;
 const index=question.index;document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);
 const cover=document.createElement('div');cover.className='pause-cover';cover.id='pause-cover';cover.innerHTML='<h2>잠깐 쉬어가요</h2><p class="muted">다른 화면을 보는 동안 시간 기록을 멈췄어요.</p><button class="primary" disabled>이어서 풀기</button>';document.body.append(cover);
 try{await game('pause',{index});cover.querySelector('button').disabled=false;cover.querySelector('button').onclick=async()=>{try{await game('resume',{index});cover.remove();document.querySelectorAll('[data-answer]').forEach(b=>b.disabled=false);}catch(e){toast('연결을 확인하고 다시 눌러주세요.');}};}catch(e){cover.querySelector('p').textContent='연결이 끊겼어요. 기록을 다시 시작해 주세요.';const b=cover.querySelector('button');b.disabled=false;b.textContent='다시 시작';b.onclick=quizIntro;}}
document.addEventListener('visibilitychange',()=>{if(document.hidden){pauseQuiz();if(screen==='selfie'){selfie?.stopCamera();toast('카메라를 껐어요. 다시 촬영하려면 카메라를 켜주세요.');$('#camera-overlay')?.removeAttribute('hidden');}}});
async function results(){const r=await game('result');question=null;sfx('win');page(`<div class="result-layout"><section class="result-card"><p class="eyebrow">MISSION COMPLETE</p><h2>작은 친구를<br>찾아줘서 고마워요!</h2><div class="score">${r.score}<small> / 5</small></div><p class="muted">풀이 시간 ${(r.duration/1000).toFixed(1)}초${practice?' · 연습 기록':''}</p><div class="stamp">참<br>잘했어요!</div><button class="primary lime" id="go-selfie">맹꽁이와 셀카 찍기 <span>↗</span></button><button class="ghost wide" style="color:#d7e4d6" id="try-again">다시 도전하기</button></section><section class="ranking"><p class="eyebrow">TODAY'S EXPLORERS</p><h2>오늘의 관찰 친구들</h2><p class="muted">정답 수가 같으면 풀이 시간이 짧은 순서예요.<br>빨리 푸는 것보다 자세히 관찰하는 게 먼저예요.</p><div id="rank-content">기록을 불러오는 중…</div>${practice?'<p class="muted">연습 모드의 기록은 다른 사람의 순위에 올라가지 않아요.</p>':`<form id="rank-form"><div class="rank-form"><input name="nickname" aria-label="순위에 표시할 별명" placeholder="별명 (2~12자)" minlength="2" maxlength="12" required><button class="primary" type="submit">기록</button></div><label class="consent"><input name="consent" type="checkbox" required>별명·정답 수·시간을 오늘의 순위에 공개해요. 기록은 30일 보관되며 현재 체험을 유지하는 동안 삭제할 수 있어요.</label></form><button id="delete-record" class="small-button" hidden>내 기록 삭제</button>`}</section></div><section class="compare">${species.map(a=>`<article><h3>${a.name}</h3><p>${a.facts.join('<br>')}</p></article>`).join('')}</section>`,'result');
 $('#go-selfie').onclick=showSelfie;$('#try-again').onclick=()=>study(0);await loadRanks();
 if(!practice){$('#rank-form').hidden=!!r.recordSaved;$('#delete-record').hidden=!r.recordSaved;$('#rank-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector('button');b.disabled=true;try{await api('rankings',{nickname:form.nickname.value.trim(),consent:form.consent.checked});form.hidden=true;$('#delete-record').hidden=false;await loadRanks();toast('오늘의 기록을 남겼어요.');}catch(e){toast(e.message);b.disabled=false;}};$('#delete-record').onclick=async()=>{try{await api('delete-record',{});$('#delete-record').hidden=true;$('#rank-form').hidden=false;$('#rank-form button').disabled=false;await loadRanks();}catch{toast('삭제에 실패했어요. 다시 눌러주세요.');}};}}
async function loadRanks(){if(practice){$('#rank-content').innerHTML='<p class="muted">현재는 순위 없는 연습 모드예요.</p>';return;}try{const data=await api('rankings');const dest=$('#rank-content');if(!dest)return;dest.innerHTML=data.rows.length?`<ol class="rank-list">${data.rows.map((r,i)=>`<li><b>${i+1}</b><span>${esc(r.nickname)}</span><span class="record">${r.score}/5 · ${(r.duration/1000).toFixed(1)}초</span></li>`).join('')}</ol>`:'<p class="muted">오늘의 첫 관찰 친구가 되어주세요!</p>';}catch{if($('#rank-content'))$('#rank-content').innerHTML='<p class="muted">순위를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.</p>';}}
function showSelfie(){page(`<section class="selfie-layout"><div class="section-head"><button class="back" id="back-result">← 결과로</button><span class="step-count">우리, 함께</span></div><div class="selfie-stage" id="selfie-stage"><div class="selfie-status" id="selfie-status">사진과 영상은 내 기기 안에서만 처리해요.</div><div class="camera-start" id="camera-overlay"><p class="eyebrow">A LITTLE FRIEND ON YOUR SHOULDER</p><h2>어깨를 살짝 빌려줘!</h2><p>귀여운 맹꽁이가 함께할게요.<br>카메라를 켜고 얼굴과 양쪽 어깨를 보여주세요.</p><button class="primary" id="camera-start">앞 카메라 켜기</button><p class="muted" id="camera-error"></p></div><button class="manual-hint" id="manual">어깨가 잘 안 잡히나요? 직접 놓기</button></div><div class="selfie-actions"><button class="secondary" id="side">반대 어깨</button><button class="primary" id="capture" disabled>사진 찍기 ○</button></div><p class="muted" style="text-align:center">실제 동물은 만지지 않고 눈으로 관찰해요.<br>셀카 속 친구는 7번을 바탕으로 만든 3D 시제품이에요.</p></section>`,'selfie');
 selfie=new Selfie($('#selfie-stage'),text=>{$('#selfie-status')&&($('#selfie-status').textContent=text);},{reduced:prefs.reduced});
 $('#back-result').onclick=()=>results().catch(e=>toast(e.message));$('#manual').onclick=()=>selfie?.useManual();$('#side').onclick=()=>selfie?.switchSide();
 $('#camera-start').onclick=async()=>{const b=$('#camera-start');b.disabled=true;try{const current=selfie;await current.start();if(current!==selfie||screen!=='selfie')return;$('#camera-overlay').hidden=true;$('#capture').disabled=false;}catch(e){if($('#camera-error'))$('#camera-error').textContent=e.name==='NotAllowedError'?'카메라 권한이 꺼져 있어요. 주소창의 카메라 권한을 허용한 뒤 다시 눌러주세요.':e.name==='NotFoundError'?'연결된 카메라를 찾지 못했어요. 카메라가 있는 휴대폰에서 열어주세요.':e.message;}finally{if(b.isConnected)b.disabled=false;}};
 $('#capture').onclick=async()=>{const b=$('#capture');b.disabled=true;try{const blob=await selfie.capture();sfx('tap');showPhoto(blob);}catch(e){toast(e.message);b.disabled=false;}};}
function showPhoto(blob){page(`<section class="selfie-layout"><p class="eyebrow">A MEMORY FROM SONGDO</p><h2>오늘, 우리 함께.</h2><img class="photo-result" id="photo" alt="맹꽁이 캐릭터와 함께 찍은 기념사진"><div class="saved-actions"><a class="primary" id="download" download="상상아트-송도-맹꽁이.png">사진 저장 ↓</a><button class="secondary" id="share">공유</button><button class="ghost" id="retake">다시 찍기</button></div><p class="muted" style="text-align:center">저장이 안 되면 사진을 길게 눌러 저장해 주세요.</p><button class="ghost wide" id="finish-home">처음으로</button></section>`,'photo');photoURL=URL.createObjectURL(blob);$('#photo').src=photoURL;$('#download').href=photoURL;$('#retake').onclick=showSelfie;$('#finish-home').onclick=home;
 const file=new File([blob],'songdo-maengkkongi.png',{type:'image/png'});if(!navigator.canShare?.({files:[file]}))$('#share').hidden=true;else $('#share').onclick=async()=>{try{await navigator.share({files:[file],title:'송도에서 만난 작은 친구'});}catch(e){if(e.name!=='AbortError')toast('공유 대신 사진 저장을 이용해 주세요.');}};}
$('#settings-open').onclick=async()=>{await pauseQuiz();$('#settings').showModal();};$('#sources-open').onclick=async()=>{await pauseQuiz();$('#sources').showModal();};
for(const [key,id] of [['sound','sound-enabled'],['haptic','haptic-enabled'],['reduced','motion-reduced']]){const input=$('#'+id);input.checked=prefs[key];input.onchange=()=>{prefs[key]=input.checked;savePrefs();document.body.classList.toggle('reduce-motion',prefs.reduced);viewers.forEach(v=>v.reduced=prefs.reduced);if(selfie)selfie.reduced=prefs.reduced;};}
document.body.classList.toggle('reduce-motion',prefs.reduced);window.addEventListener('pagehide',()=>{selfie?.stopCamera();if(question&&!answering&&!practice)navigator.sendBeacon('./api/pause',new Blob([JSON.stringify({index:question.index})],{type:'application/json'}));});
home();
